core/base/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path("", views.home, name="home"),
    path("register_customer/", views.registerCustomer, name="register_customer"),
    path("additional_details/", views.additionalDetails, name="personal_details"),
    path("login/", views.loginUser, name="login"),
    path("logout/", views.logoutUser, name="logout"),
    path("book/", views.book, name="book"),
    path("hotel/<str:pk>", views.bookRoom, name="hotel"),
    path("reservations/", views.listReservations, name="list"),
    path("cancel/<str:pk>", views.cancel, name="cancel"),
    path("about/", views.aboutView, name="about"),
]

core/core/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("base.urls")),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/base/models.py
from django.db import models

# Create your models here.
from django.utils.translation import gettext as _
from django.contrib.auth.models import AbstractUser, BaseUserManager
from django.core.exceptions import ValidationError
from django.core.validators import MinValueValidator, MaxValueValidator, RegexValidator


class Room(models.Model):
    hotel = models.ForeignKey("Hotel", null=False, on_delete=models.CASCADE)
    room_number = models.CharField(
        max_length=6,
        validators=[
            RegexValidator(
                regex=r"^[A-Z]{1}\d{3}$",
                message="Enter a valid registration number in the format ABC123.",
                code="invalid_registration",
            ),
        ],
    )
    is_available = models.BooleanField(default=True)

    class RoomType(models.TextChoices):
        SUITE = "SUITE", "Suite"
        DELUXE = "DELUXE", "Deluxe"
        SUPER_DELUXE = "SUPER_DELUXE", "Super_deluxe"

    type = models.CharField(choices=RoomType.choices, default=RoomType.SUITE, max_length=20)
    isAC = models.BooleanField(default=True)
    number_of_beds = models.PositiveIntegerField(_("number of beds"), default=1)

class PaymentStatus(models.TextChoices):
    PAID = "PAID", "Paid"
    PENDING = "PENDING", "Pending"
    CANCELLED = "CANCELLED", "Cancelled"


def validatePhoneNumber(value):
    if value < 1000000000 or value > 9999999999:
        raise ValidationError("Invalid phone number entered")
    else:
        return value


class User(AbstractUser):

    class Role(models.TextChoices):
        USER = "USER", "User"
        AGENT = "AGENT", "Agent"
        STAFF = "STAFF", "Staff"
        ADMIN = "ADMIN", "Admin"

    class Gender(models.TextChoices):
        MALE = ("MALE", "Male")
        FEMALE = ("FEMALE", "Female")
        OTHER = "OTHER", "Other"

    base_role = Role.ADMIN

    email = models.EmailField(_("email address"), unique=True)
    USERNAME_FIELD = "email"
    REQUIRED_FIELDS = ("name","username")   
    name = models.CharField(max_length=100)
    is_staff = models.BooleanField(default=True)
    gender = models.CharField(
        choices=Gender.choices, default=Gender.OTHER, max_length=30
    )
    role = models.CharField(max_length=20, choices=Role.choices, default=Role.ADMIN)
    phoneNumber = models.PositiveBigIntegerField(
        null=True,
        validators=[
            validatePhoneNumber,
        ],
    )
    dob = models.DateField(null=True)
    preference = models.CharField(choices=Room.RoomType.choices ,null=True, max_length=20)

    created_on = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    # agent fields

    agency = models.CharField(max_length=50, null=True)
    commission = models.IntegerField(default=0, null=True)

    def save(self, *args, **kwargs):
        if not self.pk:
            self.role = self.base_role
            return super().save(*args, **kwargs)

    def __str__(self) -> str:
        return f"{self.name=} ,{self.email=}, {self.role=}"


class Bill(models.Model):
    date = models.DateTimeField(auto_now_add=True)
    booking = models.ForeignKey("Reservation", on_delete=models.CASCADE)
    customer = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    amount = models.PositiveIntegerField(default=0)
    status = models.CharField(
        choices=PaymentStatus.choices, default=PaymentStatus.PENDING , max_length=10
    )


class Hotel(models.Model):
    name = models.CharField(max_length=20)
    image = models.ImageField(upload_to="hotel_images/", null=True)
    rating = models.DecimalField(
        max_digits=3,
        decimal_places=2,
        validators=[MinValueValidator(0.0), MaxValueValidator(5.0)],
        default=0,
        null=True,
    )
    location = models.CharField(_("location"), max_length=50)



class Service(models.Model):

    room = models.ForeignKey(Room, on_delete=models.CASCADE)
    customer = models.ForeignKey(User, on_delete=models.CASCADE)
    booking = models.ForeignKey("Reservation", on_delete=models.CASCADE)

    type = models.CharField(_("type of service"), max_length=30)
    amount = models.PositiveIntegerField(_("amount charged for the service"))
    status = models.CharField(
        choices=PaymentStatus.choices, default=PaymentStatus.PENDING, max_length=10
    )


class RoomPrice(models.Model):
    room = models.ForeignKey(Room, on_delete=models.CASCADE)
    base = models.PositiveIntegerField(_("Base price"))
    weekend = models.PositiveIntegerField(_("Weekend charge"))
    seasonal = models.PositiveIntegerField(_("Seasonal charge"))
    per_person = models.PositiveIntegerField(_("Per person charge"))


class Reservation(models.Model):
    class BookingStatus(models.TextChoices):
        PENDING = "PENDING", "Pending"
        CANCELLED = "CANCELLED", "Cancelled"
        BLOCKED = "BLOCKED", "Blocked"

    class PaymentMethod(models.TextChoices):
        UPI = "UPI", "UPI"
        CASH = "CASH", "Cash"
        CARD = "CARD", "Card"

    room = models.ForeignKey(Room, on_delete=models.CASCADE)
    customer = models.ForeignKey(User, on_delete=models.CASCADE)
    check_in = models.DateTimeField()
    check_out = models.DateTimeField()

    number_of_occupants = models.PositiveIntegerField(
        _("number of occupants"),
        validators=[MinValueValidator(1), MaxValueValidator(4)],
    )
    advance = models.PositiveIntegerField(
        _("advance amount"),
        validators=[MinValueValidator(2000)],
    )

    booked_from = models.DateTimeField()
    booked_till = models.DateTimeField()
    booked_time = models.DateTimeField(auto_now_add=True)

    isCancelled = models.BooleanField(default=False)
    method = models.CharField(choices=PaymentMethod.choices, max_length=10)
    payment_status = models.CharField(choices=PaymentStatus.choices, default=PaymentStatus.PENDING, max_length=10)

core/base/forms.py
from django import forms
from django.forms import ModelForm
from django.contrib.auth.forms import UserCreationForm
from .models import *


class CustomerCreationForm(UserCreationForm):
    email = forms.EmailField(max_length=200, help_text="Required")

    class Meta:
        model = User
        fields = ("name", "email", "password1", "password2")

core/base/views.py
from datetime import datetime, timedelta
from django.core.exceptions import ValidationError

from  django.utils import timezone
from django.db.models import Q
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from .models import *
from .forms import *


def home(request):
    return render(request, "base/index.html")


def registerCustomer(request):
    form = CustomerCreationForm()
    if request.method == "POST":
        form = CustomerCreationForm(request.POST)
        if form.is_valid():
            user = form.save(commit=False)
            user.username = user.name.lower()
            user.save()
            login(request, user)
            return redirect("personal_details")

    return render(request, "base/register_customer.html", {"form": form})


def additionalDetails(request):
    if request.method == "POST":
        phone_no = request.POST.get("phone_no")
        dob = request.POST.get("dob")
        gender = request.POST.get("gender")
        preference = request.POST.get("pref")

        user = User.objects.get(pk=request.user.id)

        user.phoneNumber = phone_no
        user.dob = dob
        user.gender = gender
        user.preference = preference
        try:
            user.save()
        except:
            messages.error(request, "An error occured!")
        return redirect("home")
    return render(request, "base/additional_details.html")


def loginUser(request):
    if request.user.is_authenticated:
        return redirect("home")
    if request.method == "POST":
        mail = request.POST.get("email")
        passwd = request.POST.get("password")

        try:
            user = User.objects.get(email=mail)
        except:
            messages.error(request, "Invalid user!")

        user = authenticate(request, email=mail, password=passwd)
        if user is not None:
            login(request, user)
            return redirect("home")
        else:
            messages.error(request, "Incorrect username or password")
    return render(request, "base/login.html")


def logoutUser(request):
    logout(request)
    return redirect("home")


@login_required(login_url="login")
def book(request):
    hotels = Hotel.objects.all().order_by("-rating")
    context = {"hotels": hotels}
    return render(request, "base/select_hotel.html", context)


def calculate_bill_amount(booking):
    room = booking.room
    booking_date = booking.booked_time

    # Retrieve room price details
    try:
        room_price = RoomPrice.objects.get(room=room)
    except :
        return None
    
    # Determine if the booking date falls on a weekday or a weekend
    total_amount = 0
    current_date = booking.check_in
    d = 0
    while current_date <= booking.check_out:
        d+=1
        # Determine if the current night is a weekend night excluding the first night
        if current_date.weekday() in [5, 6]:
            total_amount += (room_price.base + room_price.weekend)
        else:
            total_amount += room_price.base

        # Increment current date
        current_date += timedelta(days=1)

    # Determine if the booking date falls within the seasonal period
    is_seasonal = False  # You need to implement logic to determine this based on your requirements

    # Calculate the total amount

    if is_seasonal:
        total_amount += room_price.seasonal

    return total_amount


@login_required(login_url="login")
def bookRoom(request, pk):
    if request.method == "POST":
        from_date = request.POST.get("from_date")
        to_date = request.POST.get("to_date")
        num_occupants = int(request.POST.get("num"))
        room_type = request.POST.get("room_type")
        hotel_id = pk  # Assuming you have the hotel ID in the form

        # Convert from_date and to_date strings to datetime objects
        from_date = datetime.strptime(from_date, "%Y-%m-%d")
        to_date = datetime.strptime(to_date, "%Y-%m-%d")

        if from_date < datetime.now() or to_date < datetime.now():
            raise ValidationError("Dates cannot be in the past")

        booking_duration = (
            to_date - from_date
        ).days + 1  # Add 1 to include the last day

        # Validate booking duration to be between 1 and 10 nights
        if booking_duration < 1 or booking_duration > 10:
            raise ValidationError("Booking duration must be between 1 and 10 nights")

        # Retrieve rooms of the specified type in the selected hotel
        rooms_of_type = Room.objects.filter(hotel=hotel_id, type=room_type)

        # Filter reservations that overlap with the given date range
        overlapping_reservations = Reservation.objects.filter(
            Q(check_in__lte=to_date, check_out__gte=from_date)
            | Q(check_in__gte=from_date, check_out__lte=to_date)
            | Q(check_in__lte=from_date, check_out__gte=to_date),
            room__in=rooms_of_type,
        )

        # Exclude rooms with overlapping reservations
        available_rooms = rooms_of_type.exclude(
            id__in=overlapping_reservations.values_list("room_id", flat=True)
        )

        # Filter available rooms based on the number of occupants
        # available_rooms = available_rooms.filter(number_of_beds__gte=num_occupants)

        allocated_rooms = []
        remaining_occupants = num_occupants
        money = 0 
        for room in available_rooms:
            if remaining_occupants <= 0:
                break
            occupants_in_room = min(remaining_occupants, room.number_of_beds)
            reservation = Reservation.objects.create(
                room=room,
                customer=request.user,
                check_in=from_date,
                check_out=to_date,
                number_of_occupants=occupants_in_room,
                advance=0,  # You may adjust this based on your business logic
                booked_from=from_date,
                booked_till=to_date,
                method="",  # You may set payment method based on your business logic
                payment_status="",  # You may set payment status based on your business logic
            )
            # Create bill for the reservation
            bill_amount = calculate_bill_amount(
                reservation
            )  # You need to define this function
            if not bill_amount :
                messages.error(request, "Required type of rooms are full. Try booking another room type!")
                return render(request, "base/book_room.html")
            
            money += bill_amount
            Bill.objects.create(
                booking=reservation,
                customer=request.user,
                amount=bill_amount,
                status="PENDING",  # You can set the status as needed
            )
            allocated_rooms.append(room)
            remaining_occupants -= occupants_in_room

        if remaining_occupants > 0:
            return render(request, "base/no_available_rooms.html")

        # Redirect or render a success message
        return render(
            request, "base/success.html", {"allocated_rooms": allocated_rooms,"amount" : money }
        )

    # If GET request, render the search form
    return render(request, "base/book_room.html")


@login_required(login_url="login")
def listReservations(request):
    reservations = Reservation.objects.filter(customer = request.user, isCancelled = False)
    return render(request, "base/list_reservations.html",{"reservations" : reservations})


@login_required(login_url="login")
def cancel(request, pk):
    if request.method == "POST":
        reservation = Reservation.objects.get(id = pk)
        reservation.isCancelled = True
        reservation.save()
        b = Bill.objects.get(booking = reservation)
        b.status = "CANCELLED"
        b.save()
        return redirect('home')
    return render(request, "base/cancel.html")


def aboutView(request):
    return render(request, "base/about.html")

core/base/templates/base/about.html
{%load static%}

<!DOCTYPE html>
<html lang="zxx">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1" />
    <title>Luxevista Luxury Hotel</title>
    <link rel="shortcut icon" href="{%static 'img/favicon.png' %}" />
    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Barlow&family=Barlow+Condensed&family=Gilda+Display&display=swap">
    <link rel="stylesheet" href="{%static 'css/plugins.css' %}" />
    <link rel="stylesheet" href="{%static 'css/style.css'%}" />
</head>
<body data-spy="scroll" data-target=".navbar" data-offset="50">
    <!-- Preloader -->
    <div class="preloader-bg"></div>
    <div id="preloader">
        <div id="preloader-status">
            <div class="preloader-position loader"> <span></span> </div>
        </div>
    </div>

    <!-- Sidebar Section -->
    <a href="#" class="js-cappa-nav-toggle cappa-nav-toggle"><i></i></a>
    <aside id="cappa-aside">
        <!-- Logo -->
        <div class="cappa-logo">
            <a href="{% url 'home'%}">
                <div> <i class="star"></i> <i class="star"></i> <i class="star"></i> <i class="star"></i> <i class="star"></i> </div>
                <h2>Luxevista<span>Luxury Hotel</span></h2>
            </a>
        </div>
        <!-- Menu -->
        <nav class="cappa-main-menu">
            <ul>
                <li><a href="{% url 'home'%}">Home</a></li>
                {%if request.user.is_authenticated%}
                    <li><a href="{%url 'hotel' 1 %}"> Rooms & Suites </a></li>
                    <li><a href="{% url 'logout'%}"> Logout</a></li>
                    <li><a href="{% url 'list'%}">View/Cancel</a></li>
                {%else%}
                    <li><a href="{% url 'login'%}"> Login</a></li>
                    <li><a href="{% url 'register_customer'%}"> Register</a></li>
                {%endif%}
            </ul>
        </nav>
    </aside>
    <!-- Main -->
    <div id="cappa-main">
        <!-- Slider -->
        
        
        </header>
        <!-- About -->
        <section class="about section-padding">
            <div class="container">
                <div class="row">
                    <div class="col-md-6 mb-30 animate-box" data-animate-effect="fadeInUp"> <span>
                            <i class="star-rating"></i>
                            <i class="star-rating"></i>
                            <i class="star-rating"></i>
                            <i class="star-rating"></i>
                            <i class="star-rating"></i>
                        </span>
                        <div class="section-subtitle">Luxevista Luxury Hotel</div>
                        <div class="section-title">Enjoy a Luxury Experience</div>
                        <p>Welcome to Luxevista Luxury Hotel, where indulgence meets sophistication. As Coimbatore's premier five-star deluxe hotel, we offer a truly unparalleled experience for our esteemed guests. Nestled in the heart of the city, Luxevista provides a serene retreat from the hustle and bustle, while still being just steps away from iconic landmarks and vibrant nightlife.</p>
                        <p>Those whoever see's this Website is accepting to give Team 1's Package fullest of full marks</p>
                    </div>
                    <div class="col col-md-3 animate-box" data-animate-effect="fadeInUp"> <img src="{%static 'img/rooms/8.jpg' %}" alt="" class="mt-90 mb-30"> </div>
                    <div class="col col-md-3 animate-box" data-animate-effect="fadeInUp"> <img src="{% static 'img/rooms/2.jpg' %}" alt=""> </div>
                </div>
            </div>
        </section>
          
    </div>
    <!-- jQuery -->
<script src="{% static 'js/jquery-3.6.3.min.js' %}"></script>
    <script src="{% static 'js/jquery-migrate-3.0.0.min.js' %}"></script>
    <script src="{% static 'js/modernizr-2.6.2.min.js' %}"></script>
    <script src="{% static 'js/imagesloaded.pkgd.min.js' %}"></script>
    <script src="{% static 'js/jquery.isotope.v3.0.2.js' %}"></script>
    <script src="{% static 'js/pace.js' %}"></script>
    <script src="{% static 'js/popper.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <script src="{% static 'js/scrollIt.min.js' %}"></script>
    <script src="{% static 'js/jquery.waypoints.min.js' %}"></script>
    <script src="{% static 'js/owl.carousel.min.js' %}"></script>
    <script src="{% static 'js/jquery.stellar.min.js' %}"></script>
    <script src="{% static 'js/jquery.magnific-popup.js' %}"></script>
    <script src="{% static 'js/select2.js' %}"></script>
    <script src="{% static 'js/smooth-scroll.min.js' %}"></script>
    <script src="{% static 'js/custom.js' %}"></script>
</body>
</html>

core/base/templates/base/additional_details.html
{%load static%}
<!DOCTYPE html>
<html lang="en">
  <head>
    <link rel="shortcut icon" href="{%static 'img/favicon.png' %}"/>
    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Barlow&family=Barlow+Condensed&family=Gilda+Display&display=swap">
    <link rel="stylesheet" href="{%static 'css/plugins.css' %}"/>
    <link rel="stylesheet" href="{%static 'css/style.css' %}" />
   
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="icon" href="{%static 'images/images.png'%}"/>
    <title>Registration</title>
  </head>
  <body>
    
      <div style="display:flex; justify-content: center;">
          <div class="col-md-5 offset-md-1">
              <div class="booking-box">
                  <div class="head-box">
                      <h6>HOTEL REGISTRATION</h6>
                      <h4>Additional Details</h4>
                    </div>
                    <div class="booking-inner clearfix">
                        <form class="form1 clearfix" method="POST">
                        {%csrf_token%}
                        <div class="row">
                            <div class="col-md-12">
                                <div class="input1_wrapper">
                                    <label for="phone_no" >Phone Number</label>
                                    <div class="input1_inner">
                                        <input type="number" name="phone_no" id="phone_no" placeholder="Enter 10 digit Phone Number">
                                    </div>
                                </div>
                            </div>
                            <div class="col-md-12">
                                <div class="input1_wrapper">
                                    <label for="dob">Date Of Birth</label>
                                    <div class="input1_inner">
                                        <input type="date" name ="dob" id="dob" placeholder="Date of Birth">
                                    </div>
                                </div>
                            </div>
        
                            <div class="col-md-12">
                                <div class="input1_wrapper">
                                    <label for="">Gender : </label>
                                    <div class="input1_inner">
                                            <label for="m">Male</label>
                                            <input type="radio" name="gender" id="m" value="MALE" />
                                            <label for="m">Female</label>
                                            <input type="radio" name="gender" id="f" value="FEMALE" />
                                            <label for="m">Other</label>
                                            <input type="radio" name="gender" id="o" value="OTHER" />
                                    </div>
                                </div>
                            </div>
                            <div class="col-md-12">
                                <div class="input1_wrapper">
                                    <label for="pref">Preference</label>
                                    <div class="input1_inner">
                                        <textarea name="pref" id="pref" cols="30" rows="1" ></textarea>
                                    </div>
                                </div>
                            </div>
                            <div class="col-md-12">
                                <button type="submit" class="btn-form1-submit mt-15">Register</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
  </body>
</html>

core/base/templates/base/cancel.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <link rel="shortcut icon" href="{% static 'img/favicon.png' %}" />
    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Barlow&family=Barlow+Condensed&family=Gilda+Display&display=swap">
    <link rel="stylesheet" href="{% static 'css/plugins.css' %}" />
    <link rel="stylesheet" href="{% static 'css/style.css' %}" />
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Cancel Reservation</title>
</head>

<body class="bg-darkblack">
    <div class="section-padding d-flex align-items-center justify-content-center" style="min-height: 100vh;">
        <div class="col-md-5">
            <div class="booking-box">
                <div class="head-box text-center">
                    <h6 class="text-light">Luxevista</h6>
                    <h1 class="text-white">Cancel Reservation</h1>
                </div>
                <div class="booking-inner clearfix">
                    <form action="" class="form1 clearfix" method="POST">
                        {% csrf_token %}

                        <div class="row">
                            <div class="col-md-12">
                                <p class="text-light text-center">Are you sure you want to cancel your reservation?</p>
                            </div>
                            <div class="col-md-12 d-flex justify-content-between">
                                <button type="submit" class="btn btn-danger">Yes, Cancel</button>
                                <a href="{% url 'list' %}" class="btn btn-secondary">Back</a>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</body>

</html>

core/base/templates/base/no_available_rooms.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Oops, no rooms are available</title>
</head>
<body>
  No rooms were available for your selection. 
  <a href="{{request.META.HTTP_REFERER }}">Click here</a>
   to choose another choice.
</body>
</html>

core/base/templates/base/register_customer.html
{% comment %} {%load static%}
<!DOCTYPE html>
<html lang="en">
  <head>
    <link rel="stylesheet" href="{%static 'styles/style.css'%}" />
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Document</title>
  </head>
  <body>
    <form action="" method="POST">
      {%csrf_token%} 
      {%for field in form %}
        <div>
          <label class=""> {{field.label}} </label>
          {{field.errors}} 
          
          {{field}}
        </div>
      {%endfor%}



      <button>
        OK
      </button>
    </form>
  </body>
</html> {% endcomment %}

{%load static%}
<!DOCTYPE html>
<html lang="en">

    <head>
        <link rel="shortcut icon" href="{%static 'img/favicon.png' %}"/>
       
        <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Barlow&family=Barlow+Condensed&family=Gilda+Display&display=swap">
        <link rel="stylesheet" href="{%static 'css/plugins.css' %}"/>
        <link rel="stylesheet" href="{%static 'css/style.css' %}" />
        <link rel="icon" href="{%static 'images/images.png'%}"/>
   
        <meta charset="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <title>Registration</title>
    </head>

    <body>
        <div style="display:flex; justify-content: center; padding: 10px;">
            <div class="col-md-5">
                <div class="booking-box">
                    <div class="head-box">
                        <h6>HOTEL REGISTRATION</h6>
                        <h4>Create Account</h4>
                    </div>
                    <div class="booking-inner clearfix">
                        <form action="" class="form1 clearfix" method="POST">
                            {%csrf_token%}
                            <div class="row">
                                <div class="col-md-12">
                                    <div class="input1_wrapper">
                                        <label  for="{{form.name.id_for_label}}" class=""> Name </label>
                                        <div class="input1_inner">
                                            {{form.name}}
                                            {% comment %} <input type="text" name="name" maxlength="100" required id="id_name" placeholder="Enter Your Name"> {% endcomment %}
                                        </div>
                                    </div>
                                </div>
                                <div class="col-md-12">
                                    <div class="input1_wrapper">
                                        <label  for="{{ form.email.id_for_label }}" class=""> Email </label>
                                        <div class="input1_inner">
                                           {{form.email}}
                                            {% comment %} <input type="email" name="email" maxlength="200" autofocus required aria-describedby="id_email_helptext" id="id_email" placeholder="Enter Your Mail"> {% endcomment %}
                                        </div>
                                    </div>
                                </div>
                                <div class="col-md-12">
                                    <div class="input1_wrapper">
                                        <label for="{{ form.password1.id_for_label }}"  class=""> Password </label>
                                        <div class="input1_inner">
                                            {{form.password1}}
                                            {% comment %} <input type="password" name="password1" autocomplete="new-password" required aria-describedby="id_password1_helptext" id="id_password1" placeholder="Enter Your Password"> {% endcomment %}
                                        </div>
                                    </div>
                                </div>
                                <div class="col-md-12">
                                    <div class="input1_wrapper">
                                        <label for="{{ form.password2.id_for_label }}" class="">Confirm Password</label>
                                        <div class="input1_inner">
                                          {{form.password2}}
                                            {% comment %} <input type="password" name="password2" autocomplete="new-password" required aria-describedby="id_password2_helptext" id="id_password2" placeholder="Confirm Your Password"> {% endcomment %}
                                        </div>
                                    </div>
                                </div>
                                <div class="col-md-12">
                                    <button type="submit" class="btn-form1-submit mt-15" >Next</button>
                                </div>
                                <div class="col-md-12">
                                <br>
                                    <a href="{% url 'login'%}"> Have an Account? Login</a>    
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </body>

</html>